{{- if .Values.analytic.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hastic-analytic.serviceAccountName" . }}
  labels:
    {{- include "hastic-analytic.labels" . | nindent 4 }}
  {{- with .Values.analytic.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
